-- PostgreSQL database DDL schema - snake_case refactored

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- Tables DDL

CREATE TABLE public.titular (
    titular_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    CONSTRAINT titular_pkey PRIMARY KEY (titular_id)
);

CREATE TABLE public.account_holder (
    account_holder_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    comments text,
    CONSTRAINT account_holder_pkey PRIMARY KEY (account_holder_id)
);

CREATE TABLE public.account_type (
    account_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    code integer NOT NULL,
    CONSTRAINT account_type_pkey PRIMARY KEY (account_type_id)
);

CREATE TABLE public.currency (
    currency_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    iso_code character varying(3) NOT NULL,
    symbol character varying(10) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT currency_pkey PRIMARY KEY (currency_id)
);

CREATE TABLE public.account_group (
    account_group_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    is_hidden boolean NOT NULL,
    "order" integer NOT NULL DEFAULT 0,
    CONSTRAINT account_group_pkey PRIMARY KEY (account_group_id)
);

CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    titular_id integer NOT NULL,
    account_holder_id integer,
    sort_code character varying(50),
    number character varying(50),
    branch character varying(50),
    currency_id integer NOT NULL,
    is_closed boolean NOT NULL,
    entry date NOT NULL,
    comment text,
    name character varying(50) NOT NULL,
    is_hidden boolean NOT NULL,
    account_type_id integer NOT NULL,
    "order" integer NOT NULL DEFAULT 0,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

CREATE TABLE public.account_group_account (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_group_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT account_group_account_pkey PRIMARY KEY (id),
    CONSTRAINT account_group_account_group_id_account_id_uniq UNIQUE (account_group_id, account_id)
);

CREATE TABLE public.transaction_type (
    transaction_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    code character varying(5) NOT NULL,
    CONSTRAINT transaction_type_pkey PRIMARY KEY (transaction_type_id)
);

CREATE TABLE public.status (
    status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    CONSTRAINT status_pkey PRIMARY KEY (status_id)
);

CREATE TABLE public.category (
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    parent_category_id integer,
    is_hidden boolean NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE public.payee (
    payee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    comment text,
    CONSTRAINT payee_pkey PRIMARY KEY (payee_id)
);

CREATE TABLE public.import_csv (
    import_csv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    CONSTRAINT import_csv_pkey PRIMARY KEY (import_csv_id)
);

CREATE TABLE public.import_csv_field (
    import_csv_field_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    import_csv_id integer NOT NULL,
    name character varying(255) NOT NULL,
    map character varying(255),
    type character varying(50),
    format character varying(255),
    CONSTRAINT import_csv_field_pkey PRIMARY KEY (import_csv_field_id)
);

CREATE TABLE public.import_plan (
    import_plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    account_id integer,
    import_csv_id integer NOT NULL,
    CONSTRAINT import_plan_pkey PRIMARY KEY (import_plan_id)
);

CREATE TABLE public.import_plan_rule (
    import_plan_rule_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    import_plan_id integer NOT NULL,
    import_csv_field_id integer NOT NULL,
    pattern character varying(255) NOT NULL,
    "order" integer NOT NULL,
    ignore boolean NOT NULL,
    payee_id integer,
    category_id integer,
    to_account_id integer,
    match_type character varying(20) NOT NULL,
    CONSTRAINT import_plan_rule_pkey PRIMARY KEY (import_plan_rule_id)
);

CREATE TABLE public.transaction (
    transaction_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    transaction_type_id integer NOT NULL,
    account_id integer NOT NULL,
    status_id integer NOT NULL,
    entry timestamp with time zone NOT NULL,
    issue date,
    received date,
    refer_to date,
    due date,
    payment date,
    cash date,
    payee_id integer,
    category_id integer NOT NULL,
    comment text,
    rate double precision NOT NULL,
    amount double precision NOT NULL,
    reference character varying(50),
    transfer_transaction_id integer,
    original_amount double precision,
    original_currency_id integer,
    quantity integer,
    asset_id integer,
    CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id)
);


-- Indexes

CREATE INDEX account_group_account_account_group_id_idx ON public.account_group_account USING btree (account_group_id);
CREATE INDEX account_group_account_account_id_idx ON public.account_group_account USING btree (account_id);
CREATE INDEX account_account_holder_id_idx ON public.account USING btree (account_holder_id);
CREATE INDEX account_account_type_id_idx ON public.account USING btree (account_type_id);
CREATE INDEX account_currency_id_idx ON public.account USING btree (currency_id);
CREATE INDEX account_titular_id_idx ON public.account USING btree (titular_id);
CREATE INDEX category_parent_category_id_idx ON public.category USING btree (parent_category_id);
CREATE INDEX import_csv_field_import_csv_id_idx ON public.import_csv_field USING btree (import_csv_id);
CREATE INDEX import_plan_rule_category_id_idx ON public.import_plan_rule USING btree (category_id);
CREATE INDEX import_plan_rule_import_csv_field_id_idx ON public.import_plan_rule USING btree (import_csv_field_id);
CREATE INDEX import_plan_rule_import_plan_id_idx ON public.import_plan_rule USING btree (import_plan_id);
CREATE INDEX import_plan_rule_payee_id_idx ON public.import_plan_rule USING btree (payee_id);
CREATE INDEX import_plan_rule_to_account_id_idx ON public.import_plan_rule USING btree (to_account_id);
CREATE INDEX import_plan_account_id_idx ON public.import_plan USING btree (account_id);
CREATE INDEX import_plan_import_csv_id_idx ON public.import_plan USING btree (import_csv_id);
CREATE INDEX transaction_account_id_idx ON public.transaction USING btree (account_id);
CREATE INDEX transaction_category_id_idx ON public.transaction USING btree (category_id);
CREATE INDEX transaction_original_currency_id_idx ON public.transaction USING btree (original_currency_id);
CREATE INDEX transaction_payee_id_idx ON public.transaction USING btree (payee_id);
CREATE INDEX transaction_status_id_idx ON public.transaction USING btree (status_id);
CREATE INDEX transaction_transaction_type_id_idx ON public.transaction USING btree (transaction_type_id);
CREATE INDEX transaction_transfer_transaction_id_idx ON public.transaction USING btree (transfer_transaction_id);

-- Foreign Key Constraints

ALTER TABLE ONLY public.account_group_account
    ADD CONSTRAINT account_group_account_account_group_id_fk FOREIGN KEY (account_group_id) REFERENCES public.account_group(account_group_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.account_group_account
    ADD CONSTRAINT account_group_account_account_id_fk FOREIGN KEY (account_id) REFERENCES public.account(account_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_account_holder_id_fk FOREIGN KEY (account_holder_id) REFERENCES public.account_holder(account_holder_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_account_type_id_fk FOREIGN KEY (account_type_id) REFERENCES public.account_type(account_type_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(currency_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_titular_id_fk FOREIGN KEY (titular_id) REFERENCES public.titular(titular_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_parent_category_id_fk FOREIGN KEY (parent_category_id) REFERENCES public.category(category_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_csv_field
    ADD CONSTRAINT import_csv_field_import_csv_id_fk FOREIGN KEY (import_csv_id) REFERENCES public.import_csv(import_csv_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan_rule
    ADD CONSTRAINT import_plan_rule_category_id_fk FOREIGN KEY (category_id) REFERENCES public.category(category_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan_rule
    ADD CONSTRAINT import_plan_rule_import_csv_field_id_fk FOREIGN KEY (import_csv_field_id) REFERENCES public.import_csv_field(import_csv_field_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan_rule
    ADD CONSTRAINT import_plan_rule_import_plan_id_fk FOREIGN KEY (import_plan_id) REFERENCES public.import_plan(import_plan_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan_rule
    ADD CONSTRAINT import_plan_rule_payee_id_fk FOREIGN KEY (payee_id) REFERENCES public.payee(payee_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan_rule
    ADD CONSTRAINT import_plan_rule_to_account_id_fk FOREIGN KEY (to_account_id) REFERENCES public.account(account_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan
    ADD CONSTRAINT import_plan_account_id_fk FOREIGN KEY (account_id) REFERENCES public.account(account_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.import_plan
    ADD CONSTRAINT import_plan_import_csv_id_fk FOREIGN KEY (import_csv_id) REFERENCES public.import_csv(import_csv_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_account_id_fk FOREIGN KEY (account_id) REFERENCES public.account(account_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_category_id_fk FOREIGN KEY (category_id) REFERENCES public.category(category_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_original_currency_id_fk FOREIGN KEY (original_currency_id) REFERENCES public.currency(currency_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_payee_id_fk FOREIGN KEY (payee_id) REFERENCES public.payee(payee_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_status_id_fk FOREIGN KEY (status_id) REFERENCES public.status(status_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_transaction_type_id_fk FOREIGN KEY (transaction_type_id) REFERENCES public.transaction_type(transaction_type_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_transfer_transaction_id_fk FOREIGN KEY (transfer_transaction_id) REFERENCES public.transaction(transaction_id) DEFERRABLE INITIALLY DEFERRED;
